# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'robot_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12robot_status.proto\"H\n\x0bRobotStatus\x12\x15\n\rrobotSerialId\x18\x01 \x01(\r\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x10\n\x08isMoving\x18\x03 \x01(\x08\")\n\x12RobotStatusRequest\x12\x13\n\x0bsend_status\x18\x01 \x01(\x08\x32K\n\x12RobotStatusService\x12\x35\n\x0eGetRobotStatus\x12\x13.RobotStatusRequest\x1a\x0c.RobotStatus0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTSTATUS']._serialized_start=22
  _globals['_ROBOTSTATUS']._serialized_end=94
  _globals['_ROBOTSTATUSREQUEST']._serialized_start=96
  _globals['_ROBOTSTATUSREQUEST']._serialized_end=137
  _globals['_ROBOTSTATUSSERVICE']._serialized_start=139
  _globals['_ROBOTSTATUSSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
