# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robot_status_pb2 as robot__status__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robot_status_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotStatusServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRobotStatus = channel.unary_stream(
                '/RobotStatusService/GetRobotStatus',
                request_serializer=robot__status__pb2.RobotStatusRequest.SerializeToString,
                response_deserializer=robot__status__pb2.RobotStatus.FromString,
                _registered_method=True)


class RobotStatusServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRobotStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotStatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRobotStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRobotStatus,
                    request_deserializer=robot__status__pb2.RobotStatusRequest.FromString,
                    response_serializer=robot__status__pb2.RobotStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RobotStatusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RobotStatusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotStatusService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRobotStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/RobotStatusService/GetRobotStatus',
            robot__status__pb2.RobotStatusRequest.SerializeToString,
            robot__status__pb2.RobotStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
