#pragma once

#include <grpcpp/grpcpp.h>
// Include the generated gRPC header from the build directory
#include "robot_control_api.grpc.pb.h"

class RobotControlService final : public RobotControlServices::Service {
public:
    // The signature generated by the compiler for "returns (stream RobotStatus)"
    grpc::Status GetRobotId(grpc::ServerContext* context, const RobotIdRequest* request, RobotIdResponse* response) override ;
    grpc::Status GetBatteryLevel(grpc::ServerContext* context, const BatteryLevelRequest* request, grpc::ServerWriter<BatteryLevelResponse>* writer) override ;
    grpc::Status MoveRobotCommand(grpc::ServerContext* context, grpc::ServerReaderWriter<TelemetryResponse, MoveCommand>* stream) override ;
};