#pragma once

#include <grpcpp/grpcpp.h>
// Include the generated gRPC header from the build directory
#include "robot_status.grpc.pb.h"

class TelemetryService final : public RobotStatusService::Service {
public:
    // The signature generated by the compiler for "returns (stream RobotStatus)"
    grpc::Status GetRobotStatus(
        grpc::ServerContext* context,
        const RobotStatusRequest* request,
        grpc::ServerWriter<RobotStatus>* writer
    ) override;
};