name: Build Python Package

on: push

jobs:
  build-pypi:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: grpc_client  # <-- Points all run steps to your subfolder

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tool
        run: pip install build

      - name: Build wheel and source distribution
        run: python -m build